### ISSUE TITLE
solbuild doesnt work

### ISSUE THREAD

**Issue by ghost** [sileshn/SolusWSL#1]
it works but at the end i get this error

```
[Build] install successful
[Examine] Examining packages
Traceback (most recent call last):
  File "/usr/bin/ypkg-build", line 19, in <module>
    main()
  File "/usr/lib/python2.7/site-packages/ypkg2/main.py", line 100, in main
    build_package(args.filename, outputDir)
  File "/usr/lib/python2.7/site-packages/ypkg2/main.py", line 416, in build_package
    exaResults = exa.examine_packages(ctx, gene.packages.values())
  File "/usr/lib/python2.7/site-packages/ypkg2/examine.py", line 510, in examine_packages
    ir = self.examine_package(context, package)
  File "/usr/lib/python2.7/site-packages/ypkg2/examine.py", line 461, in examine_package
    pool = multiprocessing.Pool()
  File "/usr/lib/python2.7/multiprocessing/__init__.py", line 232, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 140, in __init__
    self._setup_queues()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 236, in _setup_queues
    self._inqueue = SimpleQueue()
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 352, in __init__
    self._rlock = Lock()
  File "/usr/lib/python2.7/multiprocessing/synchronize.py", line 147, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1)
  File "/usr/lib/python2.7/multiprocessing/synchronize.py", line 75, in __init__
    sl = self._semlock = _multiprocessing.SemLock(kind, value, maxvalue)
OSError: [Errno 38] Function not implemented
ERRO[21:10:07] Failed to build package                       error="exit status 1"
ERRO[21:10:10] Failed to build packages
```
i use "solbuild build package.yml"

**Comment by ghost** [comment]
fixed by doing

```
rm /dev/shm
mkdir /dev/shm
chmod 777 /dev/shm
```
from https://stackoverflow.com/a/26776810/5149281

**Comment by sileshn** [comment]
Fixed

**Comment by ghost** [comment]
@sileshn bro can i get your sileshnair/solus-base docker image :p

**Comment by sileshn** [comment]
Its on docker hub.

docker pull sileshnair/solus-base:unstable ( for unstable profile )
docker pull sileshnair/solus-base:main ( for main/shannon profile )
